name: SpigotMC
author: narwhql
version: 1.0
main: me.narwhql.spigotmc.Main
commands:
  armorstand:
    aliases: [as]
    description: Spawn a rotating armor stand
  pet:
    description: Spawn a pet!
  chatcolor:
    aliases: [cc]
    description: Change your chat color